export const bollywoodMovies = [
  "Dilwale Dulhania Le Jayenge",
  "3 Idiots",
  "Sholay",
  "Dangal",
  "PK",
  "Bajrangi Bhaijaan",
  "Kabhi Khushi Kabhie Gham",
  "Lagaan",
  "Zindagi Na Milegi Dobara",
  "Kuch Kuch Hota Hai",
  "Taare Zameen Par",
  "Queen",
  "Gully Boy",
  "Barfi",
  "Andhadhun",
  "Dil Chahta Hai",
  "Rang De Basanti",
  "Munna Bhai MBBS",
  "Swades",
  "Chak De India",
  "My Name is Khan",
  "Jab We Met",
  "Rockstar",
  "Yeh Jawaani Hai Deewani",
  "Udta Punjab",
  "Gangs of Wasseypur",
  "Drishyam",
  "Pink",
  "Raazi",
  "Uri: The Surgical Strike",
  "Article 15",
  "Piku",
  "Tumbbad",
  "Stree",
  "Badhaai Ho",
  "Newton",
  "Masaan",
  "Kapoor and Sons",
  "Haider",
  "Kahaani",
  "Vicky Donor",
  "English Vinglish",
  "Mary Kom",
  "Special 26",
  "Airlift",
  "Toilet Ek Prem Katha",
  "Pad Man",
  "Shubh Mangal Saavdhan",
  "October",
  "Badla",
  "Sanju",
  "War",
  "Pathaan",
  "Jawan",
  "Dhoom 3",
]
