export const bollywoodMovies = [
  // --- 1950S TO 1980S EVERGREEN CLASSICS AND MASALA HITS ---
  "Awaara",
  "Shree 420",
  "Mother India",
  "Pyaasa",
  "Chalti Ka Naam Gaadi",
  "Mughal-e-Azam",
  "Jis Desh Mein Ganga Behti Hai",
  "Junglee",
  "Kashmir Ki Kali",
  "Guide",
  "Waqt",
  "Teesri Manzil",
  "Ram Aur Shyam",
  "Jewel Thief",
  "An Evening in Paris",
  "Padosan",
  "Johny Mera Naam",
  "Mera Naam Joker",
  "Kati Patang",
  "Anand",
  "Haathi Mere Saathi",
  "Hare Rama Hare Krishna",
  "Mera Gaon Mera Desh",
  "Seeta Aur Geeta",
  "Bawarchi",
  "Bobby",
  "Zanjeer",
  "Yaadon Ki Baaraat",
  "Daag",
  "Roti Kapda Aur Makaan",
  "Sholay",
  "Deewar",
  "Chupke Chupke",
  "Khel Khel Mein",
  "Kabhi Kabhie",
  "Chhoti Si Baat",
  "Amar Akbar Anthony",
  "Hum Kisise Kum Naheen",
  "Dharam Veer",
  "Don",
  "Muqaddar Ka Sikandar",
  "Trishul",
  "Pati Patni Aur Woh",
  "Satyam Shivam Sundaram",
  "Gol Maal",
  "Mr. Natwarlal",
  "Kaala Patthar",
  "Karz",
  "Khubsoorat",
  "Dostana",
  "Shaan",
  "Laawaris",
  "Ek Duuje Ke Liye",
  "Chashme Buddoor",
  "Satte Pe Satta",
  "Namak Halaal",
  "Disco Dancer",
  "Angoor",
  "Nikaah",
  "Coolie",
  "Jaane Bhi Do Yaaro",
  "Hero",
  "Sharaabi",
  "Mard",
  "Ram Teri Ganga Maili",
  "Nagina",
  "Chameli Ki Shaadi",
  "Mr. India",
  "Tezaab",
  "Qayamat Se Qayamat Tak",
  "Khoon Bhari Maang",
  "Shahenshah",
  "Maine Pyar Kiya",
  "Chandni",
  "ChaalBaaz",
  "Ram Lakhan",
  "Sangam",
  "Aradhana",
  "Suhaag",
  "Kranti",
  "Karma",
  "Silsila",
  "Qurbani",
  "Naseeb",
  "Himmatwala",
  "Masoom",
  "Tridev",
  "Parinda",

  // --- 1990S GOLDEN ERA BLOCKBUSTERS AND ROM-COMS ---
  "Aashiqui",
  "Dil",
  "Ghayal",
  "Agneepath",
  "Phool Aur Kaante",
  "Sadak",
  "Deewana",
  "Beta",
  "Jo Jeeta Wohi Sikandar",
  "Khuda Gawah",
  "Chamatkar",
  "Raju Ban Gaya Gentleman",
  "Aankhen",
  "Baazigar",
  "Darr",
  "Khalnayak",
  "Hum Hain Rahi Pyar Ke",
  "Kabhi Haan Kabhi Naa",
  "Hum Aapke Hain Koun",
  "Andaz Apna Apna",
  "1942: A Love Story",
  "Raja Babu",
  "Main Khiladi Tu Anari",
  "Dilwale Dulhania Le Jayenge",
  "Karan Arjun",
  "Rangeela",
  "Coolie No. 1",
  "Sabse Bada Khiladi",
  "Barsaat",
  "Raja Hindustani",
  "Khamoshi",
  "Border",
  "Dil To Pagal Hai",
  "Ishq",
  "Pardes",
  "Judwaa",
  "Hero No. 1",
  "Deewana Mastana",
  "Yes Boss",
  "Chachi 420",
  "Koyla",
  "Mr. and Mrs. Khiladi",
  "Kuch Kuch Hota Hai",
  "Pyaar To Hona Hi Tha",
  "Pyaar Kiya To Darna Kya",
  "Bade Miyan Chote Miyan",
  "Ghulam",
  "Soldier",
  "Hum Saath-Saath Hain",
  "Biwi No. 1",
  "Hum Dil De Chuke Sanam",
  "Taal",
  "Haseena Maan Jaayegi",
  "Baadshah",
  "Hello Brother",
  "Hote Hote Pyar Ho Gaya",
  "Saajan",
  "Khiladi",
  "Mohra",
  "Satya",
  "Sarfarosh",

  // --- 2000S ICONIC COMEDIES, DRAMA, AND ACTION STAPLES ---
  "Kaho Naa Pyaar Hai",
  "Hera Pheri",
  "Mission Kashmir",
  "Dulhan Hum Le Jayenge",
  "Har Dil Jo Pyar Karega",
  "Phir Bhi Dil Hai Hindustani",
  "Gadar: Ek Prem Katha",
  "Kabhi Khushi Kabhie Gham",
  "Lagaan",
  "Dil Chahta Hai",
  "Nayak",
  "Rehnaa Hai Terre Dil Mein",
  "Mujhe Kucch Kehna Hai",
  "Devdas",
  "Raaz",
  "Company",
  "Awara Paagal Deewana",
  "Makdee",
  "Mere Yaar Ki Shaadi Hai",
  "Koi Mil Gaya",
  "Kal Ho Naa Ho",
  "Munna Bhai M.B.B.S.",
  "Tere Naam",
  "Baghban",
  "Hungama",
  "Bhoot",
  "Chalte Chalte",
  "Gangaajal",
  "Main Hoon Na",
  "Veer-Zaara",
  "Dhoom",
  "Mujhse Shaadi Karogi",
  "Hum Tum",
  "Murder",
  "Masti",
  "Hulchul",
  "Lakshya",
  "Khakee",
  "Black",
  "Bunty Aur Babli",
  "No Entry",
  "Garam Masala",
  "Maine Pyaar Kyun Kiya",
  "Salaam Namaste",
  "Kyaa Kool Hai Hum",
  "Paheli",
  "Sarkar",
  "Iqbal",
  "Dhoom 2",
  "Krrish",
  "Lage Raho Munna Bhai",
  "Rang De Basanti",
  "Phir Hera Pheri",
  "Vivah",
  "Kabhi Alvida Naa Kehna",
  "Golmaal",
  "Chup Chup Ke",
  "Malamaal Weekly",
  "Bhagam Bhag",
  "Khosla Ka Ghosla",
  "Om Shanti Om",
  "Chak De! India",
  "Welcome",
  "Bhool Bhulaiyaa",
  "Jab We Met",
  "Taare Zameen Par",
  "Partner",
  "Heyy Babyy",
  "Namastey London",
  "Dhamaal",
  "Dhol",
  "Bheja Fry",
  "Cheeni Kum",
  "Shootout at Lokhandwala",
  "Ghajini",
  "Rab Ne Bana Di Jodi",
  "Singh Is Kinng",
  "Jaane Tu Ya Jaane Na",
  "Fashion",
  "Race",
  "Jodhaa Akbar",
  "Rock On",
  "A Wednesday",
  "Bhoothnath",
  "Oye Lucky Lucky Oye",
  "3 Idiots",
  "Love Aaj Kal",
  "Ajab Prem Ki Ghazab Kahani",
  "Wanted",
  "Kaminey",
  "De Dana Dan",
  "Wake Up Sid",
  "Paa",
  "All the Best",
  "Rocket Singh",
  "Delhi-6",
  "Mohabbatein",
  "Dhadkan",
  "Kaante",
  "Aitraaz",
  "Omkara",
  "Guru",
  "Golmaal Returns",
  "Mujhse Dosti Karoge",
  "Chandni Chowk to China",

  // --- 2010 TO 2019 MODERN HITS AND QUIRKY SMALL-TOWN COMEDIES ---
  "Dabangg",
  "My Name Is Khan",
  "Housefull",
  "Tees Maar Khan",
  "Band Baaja Baaraat",
  "Once Upon a Time in Mumbaai",
  "Atithi Tum Kab Jaoge",
  "Khatta Meetha",
  "Do Dooni Chaar",
  "Tere Bin Laden",
  "Bodyguard",
  "Ready",
  "Singham",
  "Zindagi Na Milegi Dobara",
  "Rockstar",
  "The Dirty Picture",
  "Delhi Belly",
  "Don 2",
  "Tanu Weds Manu",
  "Mere Brother Ki Dulhan",
  "Pyar Ka Punchnama",
  "Chillar Party",
  "No One Killed Jessica",
  "7 Khoon Maaf",
  "Stanley Ka Dabba",
  "Bol Bachchan",
  "Ek Tha Tiger",
  "Rowdy Rathore",
  "Barfi",
  "Kahaani",
  "Vicky Donor",
  "English Vinglish",
  "Gangs of Wasseypur",
  "Student of the Year",
  "Son of Sardaar",
  "OMG: Oh My God",
  "Cocktail",
  "Luv Shuv Tey Chicken Khurana",
  "Paan Singh Tomar",
  "Ferrari Ki Sawaari",
  "Jab Tak Hai Jaan",
  "Chennai Express",
  "Yeh Jawaani Hai Deewani",
  "Bhaag Milkha Bhaag",
  "Aashiqui 2",
  "Goliyon Ki Raasleela Ram-Leela",
  "Special 26",
  "Fukrey",
  "Go Goa Gone",
  "Kai Po Che",
  "ABCD",
  "Phata Poster Nikhla Hero",
  "R Rajkumar",
  "Jolly LLB",
  "Matru Ki Bijlee Ka Mandola",
  "The Lunchbox",
  "PK",
  "Kick",
  "Happy New Year",
  "Queen",
  "2 States",
  "Ek Villain",
  "Mary Kom",
  "Highway",
  "Main Tera Hero",
  "Hasee Toh Phasee",
  "Dedh Ishqiya",
  "Humpty Sharma Ki Dulhania",
  "Bhoothnath Returns",
  "Daawat-e-Ishq",
  "Bajrangi Bhaijaan",
  "Tanu Weds Manu Returns",
  "Bajirao Mastani",
  "Piku",
  "Prem Ratan Dhan Payo",
  "Dil Dhadakne Do",
  "Dum Laga Ke Haisha",
  "Drishyam",
  "Baby",
  "Welcome Back",
  "Gabbar Is Back",
  "Dangal",
  "Sultan",
  "Airlift",
  "M.S. Dhoni",
  "Kapoor & Sons",
  "Ae Dil Hai Mushkil",
  "Pink",
  "Dear Zindagi",
  "Udta Punjab",
  "Sanam Teri Kasam",
  "Tiger Zinda Hai",
  "Toilet: Ek Prem Katha",
  "Hindi Medium",
  "Secret Superstar",
  "Bareilly Ki Barfi",
  "Shubh Mangal Saavdhan",
  "Badrinath Ki Dulhania",
  "Golmaal Again",
  "Tumhari Sulu",
  "Raees",
  "Sanju",
  "Padmaavat",
  "Stree",
  "Andhadhun",
  "Badhaai Ho",
  "Raazi",
  "Sonu Ke Titu Ki Sweety",
  "Pad Man",
  "Sui Dhaaga",
  "Hichki",
  "Tumbbad",
  "Veere Di Wedding",
  "War",
  "Kabir Singh",
  "Uri: The Surgical Strike",
  "Gully Boy",
  "Chhichhore",
  "Good Newwz",
  "Dream Girl",
  "Bala",
  "Mission Mangal",
  "Luka Chuppi",
  "Saand Ki Aankh",
  "Super 30",
  "De De Pyaar De",
  "Raajneeti",
  "Singham Returns",
  "Bang Bang",
  "Dilwale",
  "Neerja",
  "Rustom",
  "Simmba",
  "Raid",
  "Kesari",
  "Bharat",
  "Holiday",
  "Jab Harry Met Sejal",
  "Dhoom 3",
  "Thugs of Hindostan",

  // --- 2020 TO 2026 RECENT BLOCKBUSTERS AND HIGH-CONCEPT HITS ---
  "Tanhaji",
  "Ludo",
  "Thappad",
  "Gulabo Sitabo",
  "Angrezi Medium",
  "Shubh Mangal Zyada Saavdhan",
  "Dil Bechara",
  "Sardar Udham",
  "Atrangi Re",
  "Bhool Bhulaiyaa 2",
  "Gangubai Kathiawadi",
  "Brahmastra",
  "Bhediya",
  "Badhaai Do",
  "Jawan",
  "Pathaan",
  "Animal",
  "12th Fail",
  "Rocky Aur Rani Kii Prem Kahaani",
  "Gadar 2",
  "Tu Jhoothi Main Makkaar",
  "Zara Hatke Zara Bachke",
  "Stree 2",
  "Laapataa Ladies",
  "Teri Baaton Mein Aisa Uljha Jiya",
  "Crew",
  "Madgaon Express",
  "Chandu Champion",
  "Fighter",
  "Shaitaan",
  "Bad Newz",
  "Maidaan",
  "Sitaare Zameen Par",
  "Sunny Sanskari Ki Tulsi Kumari",
  "Dhurandhar",
  "Dhurandhar: The Revenge",
  "Chhaava",
  "Saiyaara",
  "Border 2",
  "Dunki",
  "Tiger 3",
  "Sooryavanshi",
  "War 2",
  "Raid 2",
  "Housefull 5",
  "Sikandar",
  "Thamma",
  "Mahavatar Narsimha",
  "Bhooth Bangla",
  "Dhamaal 4",
  "Welcome to the Jungle",
  "Shershaah",
  "83",
  "The Kashmir Files",
  "Munjya",
  "Singham Again",
  "Sam Bahadur",
  "Sky Force",

  // --- CLASSIC "FUNNY, LITERAL, AND CHALLENGING MULTI-WORD" CHARADES GEMS ---
  "Andheri Raat Mein Diya Tere Haath Mein",
  "Jal Bin Machhli Nritya Bin Bijli",
  "Ghar Mein Ram Gali Mein Shyam",
  "Mujhe Meri Biwi Se Bachao",
  "Main Madhuri Dixit Banna Chahti Hoon",
  "Mere Baap Pehle Aap",
  "Ek Chalis Ki Last Local",
  "Aloo Chaat",
  "Shaadi Ke Side Effects",
  "Dil Kabaddi",
  "Bbuddah Hoga Terra Baap",
  "Thoda Pyaar Thoda Magic",
  "Ek Aur Ek Gyarah",
  "Kismat Konnection",
  "Jhooth Bole Kauwa Kaate",
  "Gharwali Baharwali",
  "Taxi No. 9211",
  "Honeymoon Travels Pvt. Ltd.",
  "Manorama Six Feet Under",
  "Mard Ko Dard Nahi Hota",
  "Bank Chor",

  // --- ADDITIONAL MULTI-WORD ROM-COMS & COMEDY STAPLES ---
  "Dil Hai Ki Manta Nahin",
  "Jab Pyaar Kisise Hota Hai",
  "Chori Chori Chupke Chupke",
  "Kyo Kii Main Jhuth Nahin Bolta",
  "Aunty No. 1",
  "Apna Sapna Money Money",
  "Kabul Express",
  "Jhoom Barabar Jhoom",
  "Bachna Ae Haseeno",
  "Kambakkht Ishq",
  "Desi Boyz",
  "Ladies vs Ricky Bahl",
  "Ek Main Aur Ekk Tu",
  "Happy Bhag Jayegi",
  "Baar Baar Dekho",
  "Shaadi Mein Zaroor Aana",
  "Vicky Vidya Ka Woh Wala Video",
  "Swades",
];
