export const bollywoodMovies = [
  // --- 1950S TO 1980S EVERGREEN CLASSICS AND MASALA HITS ---
  "Awaara",
  "Baazi",
  "Do Bigha Zamin",
  "Boot Polish",
  "Nagin",
  "Shree 420",
  "Chori Chori",
  "Mother India",
  "Naya Daur",
  "Pyaasa",
  "Chalti Ka Naam Gaadi",
  "Kaagaz Ke Phool",
  "Mughal-e-Azam",
  "Jis Desh Men Ganga Behti Hai",
  "Junglee",
  "Gunga Jumna",
  "Bees Saal Baad",
  "Half Ticket",
  "Professor",
  "Bandini",
  "Taj Mahal",
  "Kashmir Ki Kali",
  "Dosti",
  "Guide",
  "Waqt",
  "Teesri Manzil",
  "Mera Saaya",
  "Ram Aur Shyam",
  "Jewel Thief",
  "An Evening in Paris",
  "Padosan",
  "Brahmachari",
  "Do Raaste",
  "Johny Mera Naam",
  "Mera Naam Joker",
  "Kati Patang",
  "Sachaa Jhutha",
  "Khilona",
  "Anand",
  "Haathi Mere Saathi",
  "Hare Rama Hare Krishna",
  "Mera Gaon Mera Desh",
  "Caravan",
  "Guddi",
  "Seeta Aur Geeta",
  "Bawarchi",
  "Victoria No. 203",
  "Bobby",
  "Zanjeer",
  "Yaadon Ki Baaraat",
  "Daag",
  "Jugnu",
  "Roti Kapda Aur Makaan",
  "Chor Machaye Shor",
  "Haath Ki Safai",
  "Kunwara Baap",
  "Sholay",
  "Deewar",
  "Chupke Chupke",
  "Khel Khel Mein",
  "Kabhi Kabhie",
  "Chhoti Si Baat",
  "Amar Akbar Anthony",
  "Hum Kisise Kum Naheen",
  "Chacha Bhatija",
  "Dharam Veer",
  "Khoon Pasina",
  "Don",
  "Muqaddar Ka Sikandar",
  "Trishul",
  "Pati Patni Aur Woh",
  "Satyam Shivam Sundaram",
  "Gol Maal",
  "Mr. Natwarlal",
  "Jaani Dushman",
  "Kaala Patthar",
  "Karz",
  "Khubsoorat",
  "Dostana",
  "Shaan",
  "Laawaris",
  "Ek Duuje Ke Liye",
  "Chashme Buddoor",
  "Satte Pe Satta",
  "Namak Halaal",
  "Disco Dancer",
  "Angoor",
  "Nikaah",
  "Coolie",
  "Jaane Bhi Do Yaaro",
  "Hero",
  "Tohfa",
  "Sharaabi",
  "Mard",
  "Ram Teri Ganga Maili",
  "Nagina",
  "Chameli Ki Shaadi",
  "Mr. India",
  "Pushpak",
  "Tezaab",
  "Qayamat Se Qayamat Tak",
  "Khoon Bhari Maang",
  "Shahenshah",
  "Maine Pyar Kiya",
  "Chandni",
  "ChaalBaaz",
  "Ram Lakhan",

  // --- 1990S GOLDEN ERA BLOCKBUSTERS AND ROM-COMS ---
  "Aashiqui",
  "Dil",
  "Ghayal",
  "Agneepath",
  "Thanedaar",
  "Phool Aur Kaante",
  "Sadak",
  "Deewana",
  "Beta",
  "Jo Jeeta Wohi Sikandar",
  "Khuda Gawah",
  "Shola Aur Shabnam",
  "Chamatkar",
  "Raju Ban Gaya Gentleman",
  "Aankhen",
  "Baazigar",
  "Darr",
  "Khalnayak",
  "Hum Hain Rahi Pyar Ke",
  "Kabhi Haan Kabhi Naa",
  "Hum Aapke Hain Koun..!",
  "Andaz Apna Apna",
  "1942: A Love Story",
  "Raja Babu",
  "Main Khiladi Tu Anari",
  "Gopi Kishan",
  "Dilwale Dulhania Le Jayenge",
  "Karan Arjun",
  "Rangeela",
  "Coolie No. 1",
  "Sabse Bada Khiladi",
  "Barsaat",
  "Ram Jaane",
  "Raja Hindustani",
  "Agni Sakshi",
  "Khamoshi: The Musical",
  "Saajan Chale Sasural",
  "Chhote Sarkar",
  "Border",
  "Dil To Pagal Hai",
  "Ishq",
  "Pardes",
  "Judwaa",
  "Gupt",
  "Hero No. 1",
  "Deewana Mastana",
  "Yes Boss",
  "Chachi 420",
  "Koyla",
  "Mr. and Mrs. Khiladi",
  "Kuch Kuch Hota Hai",
  "Pyaar To Hona Hi Tha",
  "Pyaar Kiya To Darna Kya",
  "Bade Miyan Chote Miyan",
  "Ghulam",
  "Duplicate",
  "Soldier",
  "Dulhe Raja",
  "China Gate",
  "Hum Saath-Saath Hain",
  "Biwi No. 1",
  "Hum Dil De Chuke Sanam",
  "Taal",
  "Haseena Maan Jaayegi",
  "Baadshah",
  "Jaanwar",
  "Kachche Dhaage",
  "Anari No. 1",
  "Hello Brother",
  "Hote Hote Pyar Ho Gaya",
  "Daag: The Fire",
  "Joru Ka Ghulam",

  // --- 2000S ICONIC COMEDIES, DRAMA, AND ACTION STAPLES ---
  "Kaho Naa... Pyaar Hai",
  "Hera Pheri",
  "Mission Kashmir",
  "Dulhan Hum Le Jayenge",
  "Har Dil Jo Pyar Karega",
  "Phir Bhi Dil Hai Hindustani",
  "Hadh Kar Di Aapne",
  "Gadar: Ek Prem Katha",
  "Kabhi Khushi Kabhie Gham...",
  "Lagaan",
  "Dil Chahta Hai",
  "Nayak: The Real Hero",
  "Rehnaa Hai Terre Dil Mein",
  "Mujhe Kucch Kehna Hai",
  "Jodi No. 1",
  "Aamdani Atthanni Kharcha Rupaiya",
  "Devdas",
  "Raaz",
  "Company",
  "Awara Paagal Deewana",
  "Makdee",
  "Ek Chhotisi Love Story",
  "Mere Yaar Ki Shaadi Hai",
  "Koi... Mil Gaya",
  "Kal Ho Naa Ho",
  "Munna Bhai M.B.B.S.",
  "Tere Naam",
  "Baghban",
  "Hungama",
  "Bhoot",
  "Chalte Chalte",
  "Gangaajal",
  "Main Prem Ki Diwani Hoon",
  "Qayamat: City Under Threat",
  "Main Hoon Na",
  "Veer-Zaara",
  "Dhoom",
  "Mujhse Shaadi Karogi",
  "Hum Tum",
  "Murder",
  "Masti",
  "Hulchul",
  "Lakshya",
  "Khakee",
  "Black",
  "Bunty Aur Babli",
  "No Entry",
  "Garam Masala",
  "Maine Pyaar Kyun Kiya?",
  "Salaam Namaste",
  "Waqt: The Race Against Time",
  "Kyaa Kool Hai Hum",
  "Paheli",
  "Sarkar",
  "Iqbal",
  "Dhoom 2",
  "Krrish",
  "Lage Raho Munna Bhai",
  "Rang De Basanti",
  "Phir Hera Pheri",
  "Vivah",
  "Kabhi Alvida Naa Kehna",
  "Golmaal: Fun Unlimited",
  "Chup Chup Ke",
  "Malamaal Weekly",
  "Bhagam Bhag",
  "Khosla Ka Ghosla",
  "Om Shanti Om",
  "Chak De! India",
  "Welcome",
  "Bhool Bhulaiyaa",
  "Jab We Met",
  "Taare Zameen Par",
  "Partner",
  "Heyy Babyy",
  "Namastey London",
  "Dhamaal",
  "Dhol",
  "Bheja Fry",
  "Cheeni Kum",
  "Ta Ra Rum Pum",
  "Shootout at Lokhandwala",
  "Ghajini",
  "Rab Ne Bana Di Jodi",
  "Singh Is Kinng",
  "Jaane Tu... Ya Jaane Na",
  "Fashion",
  "Race",
  "Jodhaa Akbar",
  "Rock On!!",
  "A Wednesday!",
  "Bhoothnath",
  "Oye Lucky! Lucky Oye!",
  "3 Idiots",
  "Love Aaj Kal",
  "Ajab Prem Ki Ghazab Kahani",
  "Wanted",
  "Kaminey",
  "De Dana Dan",
  "Wake Up Sid",
  "Paa",
  "All the Best: Fun Begins",
  "Rocket Singh: Salesman of the Year",
  "Delhi-6",

  // --- 2010 TO 2019 MODERN HITS AND QUIRKY SMALL-TOWN COMEDIES ---
  "Dabangg",
  "My Name Is Khan",
  "Golmaal 3",
  "Housefull",
  "Tees Maar Khan",
  "Band Baaja Baaraat",
  "Once Upon a Time in Mumbaai",
  "Atithi Tum Kab Jaoge?",
  "Khatta Meetha",
  "Phas Gaye Re Obama",
  "Do Dooni Chaar",
  "Tere Bin Laden",
  "Action Replayy",
  "Bodyguard",
  "Ready",
  "Singham",
  "Zindagi Na Milegi Dobara",
  "Rockstar",
  "The Dirty Picture",
  "Delhi Belly",
  "Don 2",
  "Tanu Weds Manu",
  "Mere Brother Ki Dulhan",
  "Pyar Ka Punchnama",
  "Chillar Party",
  "No One Killed Jessica",
  "7 Khoon Maaf",
  "Stanley Ka Dabba",
  "Shor in the City",
  "Bol Bachchan",
  "Ek Tha Tiger",
  "Rowdy Rathore",
  "Barfi!",
  "Kahaani",
  "Vicky Donor",
  "English Vinglish",
  "Gangs of Wasseypur",
  "Student of the Year",
  "Son of Sardaar",
  "OMG: Oh My God!",
  "Cocktail",
  "Luv Shuv Tey Chicken Khurana",
  "Paan Singh Tomar",
  "Ferrari Ki Sawaari",
  "Jab Tak Hai Jaan",
  "Chennai Express",
  "Yeh Jawaani Hai Deewani",
  "Bhaag Milkha Bhaag",
  "Aashiqui 2",
  "Goliyon Ki Raasleela Ram-Leela",
  "Krrish 3",
  "Special 26",
  "Fukrey",
  "Go Goa Gone",
  "Kai Po Che!",
  "ABCD: Any Body Can Dance",
  "Phata Poster Nikhla Hero",
  "R... Rajkumar",
  "Shuddh Desi Romance",
  "Nautanki Saala!",
  "Jolly LLB",
  "Matru Ki Bijlee Ka Mandola",
  "The Lunchbox",
  "PK",
  "Kick",
  "Happy New Year",
  "Queen",
  "2 States",
  "Ek Villain",
  "Mary Kom",
  "Highway",
  "Main Tera Hero",
  "Hasee Toh Phasee",
  "Dedh Ishqiya",
  "Humpty Sharma Ki Dulhania",
  "Bhoothnath Returns",
  "Daawat-e-Ishq",
  "Bajrangi Bhaijaan",
  "Tanu Weds Manu Returns",
  "Bajirao Mastani",
  "Piku",
  "Prem Ratan Dhan Payo",
  "Dil Dhadakne Do",
  "Dum Laga Ke Haisha",
  "Drishyam",
  "Baby",
  "Welcome Back",
  "Gabbar Is Back",
  "Dangal",
  "Sultan",
  "Airlift",
  "M.S. Dhoni: The Untold Story",
  "Kapoor & Sons",
  "Ae Dil Hai Mushkil",
  "Pink",
  "Dear Zindagi",
  "Udta Punjab",
  "Sanam Teri Kasam",
  "Baahubali 2: The Conclusion",
  "Tiger Zinda Hai",
  "Toilet: Ek Prem Katha",
  "Hindi Medium",
  "Secret Superstar",
  "Bareilly Ki Barfi",
  "Shubh Mangal Saavdhan",
  "Judwaa 2",
  "Badrinath Ki Dulhania",
  "Golmaal Again",
  "Tumhari Sulu",
  "Raees",
  "Sanju",
  "Padmaavat",
  "Stree",
  "Andhadhun",
  "Badhaai Ho",
  "Raazi",
  "Sonu Ke Titu Ki Sweety",
  "Pad Man",
  "Sui Dhaaga",
  "Hichki",
  "Tumbbad",
  "Veere Di Wedding",
  "War",
  "Kabir Singh",
  "Uri: The Surgical Strike",
  "Gully Boy",
  "Chhichhore",
  "Good Newwz",
  "Dream Girl",
  "Bala",
  "Mission Mangal",
  "Luka Chuppi",
  "Saand Ki Aankh",
  "Super 30",
  "De De Pyaar De",

  // --- 2020 TO 2026 RECENT BLOCKBUSTERS AND HIGH-CONCEPT HITS ---
  "Tanhaji: The Unsung Warrior",
  "Ludo",
  "Thappad",
  "Gulabo Sitabo",
  "Lootcase",
  "Angrezi Medium",
  "Shubh Mangal Zyada Saavdhan",
  "Dil Bechara",
  "Sardar Udham",
  "Atrangi Re",
  "Bhool Bhulaiyaa 2",
  "Gangubai Kathiawadi",
  "Brahmastra: Part One: Shiva",
  "Drishyam 2",
  "Bhediya",
  "Monica, O My Darling",
  "Badhaai Do",
  "Doctor G",
  "Jawan",
  "Pathaan",
  "Animal",
  "12th Fail",
  "Rocky Aur Rani Kii Prem Kahaani",
  "Gadar 2",
  "Tu Jhoothi Main Makkaar",
  "OMG 2",
  "Kathal",
  "Zara Hatke Zara Bachke",
  "Fukrey 3",
  "Chor Nikal Ke Bhaga",
  "Stree 2",
  "Laapataa Ladies",
  "Teri Baaton Mein Aisa Uljha Jiya",
  "Crew",
  "Madgaon Express",
  "Chandu Champion",
  "Fighter",
  "Shaitaan",
  "Bhool Bhulaiyaa 3",
  "Bad Newz",
  "Maidaan",
  "Sitaare Zameen Par",
  "Sunny Sanskari Ki Tulsi Kumari",

  // --- CLASSIC "FUNNY, LITERAL, AND CHALLENGING MULTI-WORD" CHARADES GEMS ---
  "Andheri Raat Mein Diya Tere Haath Mein",
  "Jal Bin Machhli Nritya Bin Bijli",
  "Ghar Mein Ram Gali Mein Shyam",
  "Mujhe Meri Biwi Se Bachao",
  "Main Madhuri Dixit Banna Chahti Hoon",
  "Mere Baap Pehle Aap",
  "Ek Chalis Ki Last Local",
  "Aloo Chaat",
  "Shaadi Ke Side Effects",
  "Dil Kabaddi",
  "Bbuddah... Hoga Terra Baap",
  "Thoda Pyaar Thoda Magic",
  "Ek Aur Ek Gyarah",
  "Chor Police",
  "Daal Mein Kaala",
  "Teesra Kaun?",
  "Kismat Konnection",
  "Jhooth Bole Kauwa Kaate",
  "Gharwali Baharwali",
  "Kunwara",
  "Aag Hi Aag",
  "Taxi No. 9211",
  "Chain Kulii Ki Main Kulii",
  "Honeymoon Travels Pvt. Ltd.",
  "Manorama Six Feet Under",
  "Well Done Abba",
  "Saheb, Biwi Aur Gangster",
  "Pataakha",
  "Mard Ko Dard Nahi Hota",
  "Bank Chor",
  "Qarib Qarib Singlle",

  // --- ADDITIONAL MULTI-WORD ROM-COMS & COMEDY STAPLES ---
  "Dil Hai Ki Manta Nahin",
  "Jab Pyaar Kisise Hota Hai",
  "Chori Chori Chupke Chupke",
  "Kyo Kii... Main Jhuth Nahin Bolta",
  "Aunty No. 1",
  "Chal Mere Bhai",
  "Tujhe Meri Kasam",
  "Dil Maange More",
  "Shaadi No. 1",
  "Maine Pyaar Kyun Kiya",
  "Apna Sapna Money Money",
  "Kabul Express",
  "Jhoom Barabar Jhoom",
  "Bachna Ae Haseeno",
  "Kambakkht Ishq",
  "All The Best: Fun Begins",
  "Desi Boyz",
  "Ladies vs Ricky Bahl",
  "Ek Main Aur Ekk Tu",
  "Chashme Baddoor",
  "Happy Bhag Jayegi",
  "Baar Baar Dekho",
  "Shaadi Mein Zaroor Aana",
  "Vicky Vidya Ka Woh Wala Video",
  "Swades",
];
