export const britishMovies = [
  "The King's Speech",
  "Billy Elliot",
  "Trainspotting",
  "Notting Hill",
  "Bridget Jones's Diary",
  "The Full Monty",
  "28 Days Later",
  "Shaun of the Dead",
  "Hot Fuzz",
  "The World's End",
  "Snatch",
  "Lock Stock and Two Smoking Barrels",
  "The Imitation Game",
  "The Theory of Everything",
  "Rocketman",
  "The Favourite",
  "Atonement",
  "Pride and Prejudice",
  "Emma",
]
