export const britishMovies = [
  "Harry Potter and the Philosopher's Stone",
  "Harry Potter and the Chamber of Secrets",
  "Harry Potter and the Prisoner of Azkaban",
  "Harry Potter and the Goblet of Fire",
  "Harry Potter and the Deathly Hallows",
  "James Bond Skyfall",
  "James Bond Casino Royale",
  "James Bond Spectre",
  "The King's Speech",
  "Slumdog Millionaire",
  "Paddington",
  "Billy Elliot",
  "Trainspotting",
  "Love Actually",
  "Four Weddings and a Funeral",
  "Notting Hill",
  "Bridget Jones's Diary",
  "Bend It Like Beckham",
  "The Full Monty",
  "28 Days Later",
  "Shaun of the Dead",
  "Hot Fuzz",
  "The World's End",
  "Snatch",
  "Lock Stock and Two Smoking Barrels",
  "The Imitation Game",
  "The Theory of Everything",
  "Bohemian Rhapsody",
  "Rocketman",
  "1917",
  "Dunkirk",
  "The Favourite",
  "Atonement",
  "Pride and Prejudice",
  "Emma",
]
