export const frenchMovies = [
  "Amélie",
  "The Intouchables",
  "La Vie en Rose",
  "The Artist",
  "Blue Is the Warmest Colour",
  "Portrait of a Lady on Fire",
  "The 400 Blows",
  "Breathless",
  "Léon The Professional",
  "La Haine",
  "Irreversible",
  "A Prophet",
  "Tell No One",
  "The Class",
  "Rust and Bone",
  "Amour",
  "Incendies",
  "The Beat That My Heart Skipped",
  "A Very Long Engagement",
  "Delicatessen",
  "The City of Lost Children",
  "La Femme Nikita",
  "Three Colors Red",
  "Three Colors Blue",
  "Three Colors White",
  "The Diving Bell and the Butterfly",
  "Les Misérables",
  "Taken",
  "Lucy",
]
