export const hollywoodMovies = [
  "The Shawshank Redemption",
  "The Dark Knight",
  "Forrest Gump",
  "Inception",
  "The Matrix",
  "Titanic",
  "Avatar",
  "Interstellar",
  "The Godfather",
  "Pulp Fiction",
  "Fight Club",
  "The Avengers",
  "Jurassic Park",
  "Star Wars",
  "The Lion King",
  "Gladiator",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "Schindler's List",
  "The Green Mile",
  "Good Will Hunting",
  "The Departed",
  "The Prestige",
  "Memento",
  "The Usual Suspects",
  "Se7en",
  "The Sixth Sense",
  "American Beauty",
  "Catch Me If You Can",
  "The Truman Show",
  "Eternal Sunshine of the Spotless Mind",
  "Shutter Island",
  "The Wolf of Wall Street",
  "Django Unchained",
  "Inglourious Basterds",
  "Kill Bill",
  "Reservoir Dogs",
  "The Big Lebowski",
  "No Country for Old Men",
  "There Will Be Blood",
  "The Social Network",
  "Gone Girl",
  "Zodiac",
  "Prisoners",
  "Arrival",
  "Blade Runner 2049",
  "Mad Max Fury Road",
  "Dunkirk",
  "1917",
  "Joker",
  "Logan",
  "Spider-Man Into the Spider-Verse",
  "Black Panther",
  "Guardians of the Galaxy",
  "Iron Man",
  "Captain America Civil War",
  "Avengers Endgame",
  "The Batman",
  "Dune",
  "Oppenheimer",
  "Everything Everywhere All at Once",
  "Parasite",
  "Get Out",
  "A Quiet Place",
  "The Grand Budapest Hotel",
  "Moonlight",
  "La La Land",
  "Whiplash",
  "Her",
  "Ex Machina",
  "The Martian",
  "Edge of Tomorrow",
  "Mission Impossible Fallout",
  "Top Gun Maverick",
  "Fast and Furious",
  "John Wick",
  "The Bourne Identity",
  "Casino Royale",
  "Pirates of the Caribbean",
  "The Lord of the Rings",
  "The Hobbit",
]
