export const hollywoodMovies = [
  // Disney animation classics
  "Snow White",
  "Pinocchio",
  "Dumbo",
  "Bambi",
  "Cinderella",
  "Alice in Wonderland",
  "Peter Pan",
  "Lady and the Tramp",
  "Sleeping Beauty",
  "101 Dalmatians",
  "The Jungle Book",
  "The Little Mermaid",
  "Beauty and the Beast",
  "Aladdin",
  "The Lion King",
  "Hercules",
  "Tarzan",
  "Lilo and Stitch",
  "Brother Bear",
  "Chicken Little",
  "Bolt",
  "The Princess and the Frog",
  "Winnie the Pooh",
  "Tangled",
  "Wreck-It Ralph",
  "Frozen",
  "Big Hero 6",
  "Zootopia",
  "Moana",
  "Mary Poppins",
  "Maleficent",
  "Mufasa",
  "The Nightmare Before Christmas",

  // Pixar
  "Toy Story",
  "A Bug's Life",
  "Monsters Inc",
  "Finding Nemo",
  "The Incredibles",
  "Cars",
  "Ratatouille",
  "WALL-E",
  "Up",
  "Brave",
  "Inside Out",
  "The Good Dinosaur",
  "Coco",
  "Turning Red",
  "Lightyear",
  "Elemental",
  "Hoppers",

  // DreamWorks
  "Shrek",
  "The Prince of Egypt",
  "Chicken Run",
  "Shark Tale",
  "Madagascar",
  "Over the Hedge",
  "Flushed Away",
  "Bee Movie",
  "Kung Fu Panda",
  "Monsters vs Aliens",
  "How to Train Your Dragon",
  "Megamind",
  "Puss in Boots",
  "The Croods",
  "Trolls",
  "The Boss Baby",
  "The Bad Guys",
  "The Wild Robot",

  // Illumination, Sony, Blue Sky, Warner and other animation
  "Despicable Me",
  "Minions",
  "The Secret Life of Pets",
  "Sing",
  "The Grinch",
  "The Super Mario Bros Movie",
  "Ice Age",
  "Happy Feet",
  "Cloudy with a Chance of Meatballs",
  "Hotel Transylvania",
  "The Smurfs",
  "The Angry Birds Movie",
  "The Lego Movie",
  "The Polar Express",
  "Spider-Man Into the Spider-Verse",
  "KPop Demon Hunters",

  // Marvel
  "Iron Man",
  "The Incredible Hulk",
  "Thor",
  "Captain America",
  "The Avengers",
  "Guardians of the Galaxy",
  "Ant-Man",
  "Captain America Civil War",
  "Doctor Strange",
  "Black Panther",
  "Avengers Infinity War",
  "Captain Marvel",
  "Avengers Endgame",
  "Black Widow",
  "Spider-Man",
  "Spider-Man No Way Home",
  "Spider-Man Brand New Day",
  "X-Men",
  "Deadpool",
  "Deadpool and Wolverine",
  "Venom",
  "Fantastic Four",
  "Ghost Rider",
  "Blade",

  // DC and other superheroes
  "Superman",
  "Man of Steel",
  "The Dark Knight",
  "The Batman",
  "Joker",
  "Wonder Woman",
  "Aquaman",
  "Justice League",
  "Suicide Squad",
  "The Flash",
  "Green Lantern",
  "Catwoman",
  "The Mask",
  "Hellboy",

  // Sci-fi and fantasy franchises
  "Star Wars",
  "Star Trek",
  "Harry Potter and the Philosopher's Stone",
  "Harry Potter and the Chamber of Secrets",
  "Harry Potter and the Prisoner of Azkaban",
  "Harry Potter and the Goblet of Fire",
  "Harry Potter and the Deathly Hallows",
  "Fantastic Beasts and Where to Find Them",
  "The Lord of the Rings",
  "The Hobbit",
  "The Chronicles of Narnia",
  "Pirates of the Caribbean",
  "Jurassic Park",
  "Jurassic World",
  "Avatar",
  "Avatar The Way of Water",
  "Transformers",
  "The Matrix",
  "The Terminator",
  "Alien",
  "Predator",
  "Planet of the Apes",
  "King Kong",
  "Godzilla",
  "Pacific Rim",
  "Men in Black",
  "Independence Day",
  "Back to the Future",
  "E.T. the Extra-Terrestrial",
  "Ghostbusters",
  "Twilight",
  "The Hunger Games",
  "The Maze Runner",
  "Clash of the Titans",
  "Prince of Persia",
  "Dune",

  // Space and disaster
  "Interstellar",
  "Inception",
  "Gravity",
  "The Martian",
  "Armageddon",
  "The Day After Tomorrow",
  "Twister",
  "War of the Worlds",
  "World War Z",
  "I Am Legend",
  "I Robot",
  "Edge of Tomorrow",
  "Total Recall",
  "RoboCop",
  "Real Steel",
  "Ready Player One",
  "Free Guy",
  "Project Hail Mary",

  // Action and adventure
  "Die Hard",
  "Lethal Weapon",
  "Speed",
  "Rambo",
  "Rocky",
  "Commando",
  "True Lies",
  "The Rock",
  "Con Air",
  "Face Off",
  "Air Force One",
  "Cliffhanger",
  "The Fugitive",
  "Point Break",
  "Bad Boys",
  "Rush Hour",
  "Gone in 60 Seconds",
  "The Fast and the Furious",
  "Taken",
  "The Transporter",
  "The Expendables",
  "John Wick",
  "Mad Max Fury Road",
  "Top Gun",
  "Top Gun Maverick",
  "Gladiator",
  "Troy",
  "Braveheart",
  "The Last Samurai",
  "Raiders of the Lost Ark",
  "The Mummy",
  "The Scorpion King",
  "The Mask of Zorro",
  "Robin Hood",
  "National Treasure",
  "Tomb Raider",
  "Jumanji",
  "Black Hawk Down",
  "Pearl Harbor",
  "Enter the Dragon",
  "Crouching Tiger Hidden Dragon",
  "Kung Fu Hustle",
  "Kill Bill",
  "The Karate Kid",
  "Extraction",
  "The Gray Man",
  "Bullet Train",
  "F1",

  // Spy, heist and crime
  "Mission Impossible",
  "The Bourne Identity",
  "Casino Royale",
  "Skyfall",
  "GoldenEye",
  "Goldfinger",
  "Tomorrow Never Dies",
  "Die Another Day",
  "No Time to Die",
  "Kingsman",
  "Mr and Mrs Smith",
  "Charlie's Angels",
  "Ocean's Eleven",
  "The Italian Job",
  "Now You See Me",
  "Baby Driver",
  "Red Notice",
  "Heart of Stone",
  "Knives Out",
  "Sherlock Holmes",
  "The Da Vinci Code",
  "Angels and Demons",
  "Catch Me If You Can",
  "The Godfather",
  "Pulp Fiction",
  "The Wolf of Wall Street",

  // Video game adaptations
  "Mortal Kombat",
  "Resident Evil",
  "Sonic the Hedgehog",
  "Detective Pikachu",
  "Uncharted",
  "Assassin's Creed",
  "A Minecraft Movie",
  "Five Nights at Freddy's",

  // Comedy
  "Home Alone",
  "Baby's Day Out",
  "Mrs Doubtfire",
  "Ace Ventura",
  "Liar Liar",
  "Dumb and Dumber",
  "Bruce Almighty",
  "Yes Man",
  "The Nutty Professor",
  "Doctor Dolittle",
  "Coming to America",
  "Beverly Hills Cop",
  "Police Academy",
  "Airplane",
  "The Naked Gun",
  "The Pink Panther",
  "Johnny English",
  "Mr Bean's Holiday",
  "Twins",
  "Big",
  "Groundhog Day",
  "Night at the Museum",
  "Meet the Parents",
  "The Hangover",
  "Wedding Crashers",
  "White Chicks",
  "Scary Movie",
  "American Pie",
  "21 Jump Street",
  "Zoolander",
  "School of Rock",
  "Click",
  "Big Daddy",
  "Anger Management",
  "Grown Ups",
  "Murder Mystery",
  "Ted",
  "Mean Girls",
  "Legally Blonde",
  "The Devil Wears Prada",
  "The Intern",
  "Don't Look Up",
  "Barbie",

  // Rom-com and romance
  "Pretty Woman",
  "Ghost",
  "Dirty Dancing",
  "Sleepless in Seattle",
  "You've Got Mail",
  "When Harry Met Sally",
  "Four Weddings and a Funeral",
  "Runaway Bride",
  "My Big Fat Greek Wedding",
  "10 Things I Hate About You",
  "The Wedding Planner",
  "Hitch",
  "50 First Dates",
  "How to Lose a Guy in 10 Days",
  "Just Go with It",
  "The Proposal",
  "Crazy Stupid Love",
  "Love Actually",
  "500 Days of Summer",
  "The Notebook",
  "A Walk to Remember",
  "Titanic",
  "The Fault in Our Stars",
  "Crazy Rich Asians",
  "Eat Pray Love",
  "To All the Boys I've Loved Before",
  "The Princess Diaries",
  "Freaky Friday",
  "The Bodyguard",

  // Family and kids live action
  "Honey I Shrunk the Kids",
  "Stuart Little",
  "Beethoven",
  "Free Willy",
  "Casper",
  "Hook",
  "The Parent Trap",
  "Cheaper by the Dozen",
  "Spy Kids",
  "Charlie and the Chocolate Factory",
  "Paddington",
  "Elf",
  "Diary of a Wimpy Kid",
  "Mr Popper's Penguins",
  "Marley and Me",
  "Hachi A Dog's Tale",
  "A Dog's Purpose",
  "Scooby-Doo",
  "Garfield",
  "Alvin and the Chipmunks",
  "Tom and Jerry",
  "Space Jam",
  "The Addams Family",

  // Musicals and dance
  "The Sound of Music",
  "Singin' in the Rain",
  "West Side Story",
  "Chitty Chitty Bang Bang",
  "Grease",
  "Mamma Mia",
  "Sister Act",
  "Step Up",
  "Pitch Perfect",
  "The Greatest Showman",
  "La La Land",
  "A Star Is Born",
  "Bohemian Rhapsody",
  "Wicked",
  "Michael",

  // Horror and thriller
  "Psycho",
  "The Birds",
  "The Exorcist",
  "The Shining",
  "Jaws",
  "Halloween",
  "A Nightmare on Elm Street",
  "Child's Play",
  "Evil Dead",
  "Dracula",
  "Frankenstein",
  "The Invisible Man",
  "Scream",
  "I Know What You Did Last Summer",
  "Final Destination",
  "The Ring",
  "The Grudge",
  "Wrong Turn",
  "Saw",
  "Paranormal Activity",
  "The Conjuring",
  "Annabelle",
  "The Nun",
  "It",
  "Don't Breathe",
  "Split",
  "The Sixth Sense",
  "Get Out",
  "A Quiet Place",
  "Bird Box",
  "Smile",
  "Weapons",
  "Zombieland",
  "Anaconda",
  "Deep Blue Sea",
  "The Meg",
  "Snakes on a Plane",
  "The Silence of the Lambs",
  "Shutter Island",
  "Gone Girl",
  "Fight Club",
  "Black Swan",

  // Drama and Oscar favourites that still mime well
  "Forrest Gump",
  "The Shawshank Redemption",
  "The Green Mile",
  "Good Will Hunting",
  "Saving Private Ryan",
  "Cast Away",
  "The Terminal",
  "Rain Man",
  "Dead Poets Society",
  "A Few Good Men",
  "Patch Adams",
  "The Truman Show",
  "The Pursuit of Happyness",
  "The Curious Case of Benjamin Button",
  "Million Dollar Baby",
  "Blood Diamond",
  "The Social Network",
  "The Great Gatsby",
  "Life of Pi",
  "Slumdog Millionaire",
  "Lion",
  "Bend It Like Beckham",
  "Oppenheimer",
  "The Odyssey",

  // Timeless classics before 1980
  "Gone with the Wind",
  "The Wizard of Oz",
  "The Great Escape",
  "The Good the Bad and the Ugly",
  "Taxi Driver",
]
