export const japaneseMovies = [
  "Spirited Away",
  "Your Name",
  "Princess Mononoke",
  "My Neighbor Totoro",
  "Howl's Moving Castle",
  "Grave of the Fireflies",
  "Akira",
  "Seven Samurai",
  "Rashomon",
  "Tokyo Story",
  "Ikiru",
  "Ran",
  "Yojimbo",
  "High and Low",
  "Kagemusha",
  "Battle Royale",
  "Ringu",
  "Ju-On The Grudge",
  "Dark Water",
  "Audition",
  "Departures",
  "Shoplifters",
  "Nobody Knows",
  "Still Walking",
  "After Life",
  "Shall We Dance",
  "Love Letter",
  "Weathering with You",
  "A Silent Voice",
  "Wolf Children",
  "The Girl Who Leapt Through Time",
  "Summer Wars",
  "Perfect Blue",
  "Paprika",
  "Tokyo Godfathers",
]
