export const koreanMovies = [
  "Parasite",
  "Oldboy",
  "Train to Busan",
  "The Handmaiden",
  "Memories of Murder",
  "Burning",
  "The Host",
  "Mother",
  "I Saw the Devil",
  "The Wailing",
  "A Bittersweet Life",
  "The Chaser",
  "The Man from Nowhere",
  "New World",
  "The Thieves",
  "Assassination",
  "The Admiral",
  "Along with the Gods",
  "Extreme Job",
  "Exit",
  "Steel Rain",
  "Veteran",
  "The Outlaws",
  "A Taxi Driver",
  "1987 When the Day Comes",
  "The Battleship Island",
  "Ode to My Father",
  "Miracle in Cell No. 7",
  "The Attorney",
  "Masquerade",
  "The Throne",
  "The Handmaiden",
  "Okja",
  "Snowpiercer",
  "Peninsula",
]
