export const southIndianMovies = [
  // --- TELUGU ---
  "Baahubali",
  "Baahubali 2",
  "RRR",
  "Pushpa",
  "Pushpa 2",
  "Kalki 2898 AD",
  "Salaar",
  "Saaho",
  "Devara",
  "Makkhi (Eega)",
  "Magadheera",
  "Arjun Reddy",
  "Hanu-Man",
  "Karthikeya 2",
  "Sita Ramam",
  "Adipurush",
  "Radhe Shyam",
  "Liger",
  "Major",
  "The Ghazi Attack",
  "Dasara",
  "Game Changer",
  "The RajaSaab",
  "They Call Him OG",
  "Hi Papa (Hi Nanna)",
  "Kushi",
  "Lucky Baskhar",
  "Tiger Nageswara Rao",
  "Gabbar Singh",
  "Vakeel Saab",
  "Jersey",
  "Shiva",
  "DJ",
  "Businessman",
  "Temper",
  "Mirchi",
  "Rebel",
  "Darling",
  "Mr. Perfect",
  "Spyder",
  "Dhamaka",
  "Khaidi No. 150",
  "Yamadonga",
  "Chatrapathi",
  "Mass",
  "Legend",
  "Simha",
  "Bheeshma",

  // --- TAMIL ---
  "Robot (Enthiran)",
  "2.0",
  "Sivaji: The Boss",
  "Vikram",
  "Jailer",
  "Leo",
  "Master",
  "Beast",
  "Kaithi",
  "Vikram Vedha",
  "Kabali",
  "Jai Bhim",
  "Maharaja",
  "Hindustani (Indian)",
  "Roja",
  "Bombay",
  "Aparichit (Anniyan)",
  "Kaala",
  "Darbar",
  "Vettaiyan",
  "Asuran",
  "Amaran",
  "The Greatest of All Time",
  "Good Bad Ugly",
  "Captain Miller",
  "Sardar",
  "Doctor",
  "Love Today",
  "Raja Rani",
  "Ratsasan",
  "Kanchana",
  "Chandramukhi",
  "Dasavathaaram",
  "Vishwaroop (Vishwaroopam)",
  "Jeans",
  "Humse Hai Muqabala (Kadhalan)",
  "Pizza",

  // --- MALAYALAM ---
  "Manjummel Boys",
  "Premalu",
  "Aavesham",
  "Minnal Murali",
  "The Goat Life (Aadujeevitham)",
  "Lucifer",
  "Marco",
  "Lokah Chapter 1: Chandra",
  "Premam",
  "Bangalore Days",
  "Kumbalangi Nights",
  "Hridayam",
  "The Great Indian Kitchen",
  "Driving Licence",
  "Traffic",
  "Mumbai Police",
  "Jallikattu",
  "Malik",
  "Ustad Hotel",
  "Pulimurugan",
  "Kishkindha Kaandam",

  // --- KANNADA ---
  "KGF: Chapter 1",
  "KGF: Chapter 2",
  "Kantara",
  "Kantara: Chapter 1",
  "777 Charlie",
  "Toxic",
  "Vikrant Rona",
  "Pailwaan",
  "Kabzaa",
  "Bagheera",
  "Kurukshetra",
  "Kirik Party",
  "U Turn",
  "Lucia",
]
