export const tollywoodMovies = [
  "Baahubali",
  "Baahubali 2",
  "RRR",
  "Eega",
  "Magadheera",
  "Arjun Reddy",
  "Rangasthalam",
  "Ala Vaikunthapurramuloo",
  "Pushpa",
  "Pushpa 2",
  "Srimanthudu",
  "Athadu",
  "Okkadu",
  "Pokiri",
  "Dookudu",
  "Sye",
  "Jalsa",
  "Gabbar Singh",
  "Attarintiki Daredi",
  "S/O Satyamurthy",
  "Ninnu Kori",
  "Geetha Govindam",
  "Fidaa",
  "Jersey",
  "Majili",
  "Sarileru Neekevvaru",
  "Akhanda",
  "Krack",
  "Uppena",
  "Vakeel Saab",
  "DJ Tillu",
  "Karthikeya 2",
  "Sita Ramam",
  "HIT",
  "Jathi Ratnalu",
  "Colour Photo",
  "C/O Kancharapalem",
  "Pelli Choopulu",
  "Arjun Suravaram",
  "Nani's Gang Leader",
  "Saaho",
]
