export const worldCinemaMovies = [
  // --- KOREAN ---
  "Parasite",
  "Train to Busan",
  "Peninsula",
  "Oldboy",
  "The Host",
  "Okja",
  "Snowpiercer",
  "Miracle in Cell No. 7",
  "The Man from Nowhere",
  "Along with the Gods",
  "Exit",
  "I Saw the Devil",
  "Memories of Murder",
  "The Handmaiden",
  "Extreme Job",

  // --- JAPANESE (ANIME AND LIVE ACTION) ---
  "Spirited Away",
  "My Neighbor Totoro",
  "Howl's Moving Castle",
  "Princess Mononoke",
  "Ponyo",
  "Kiki's Delivery Service",
  "Castle in the Sky",
  "The Boy and the Heron",
  "Grave of the Fireflies",
  "Your Name",
  "Weathering with You",
  "Suzume",
  "A Silent Voice",
  "Akira",
  "Demon Slayer: Mugen Train",
  "Demon Slayer: Infinity Castle",
  "Jujutsu Kaisen 0",
  "Dragon Ball Super: Broly",
  "Stand by Me Doraemon",
  "Pokemon: The First Movie",
  "Godzilla Minus One",
  "Seven Samurai",
  "Battle Royale",
  "Shoplifters",

  // --- BRITISH ---
  "The King's Speech",
  "Notting Hill",
  "Bridget Jones's Diary",
  "The Imitation Game",
  "The Theory of Everything",
  "Pride and Prejudice",
  "Snatch",

  // --- EUROPEAN ---
  "Amelie",
  "The Intouchables",
  "Leon: The Professional",
  "Lucy",
  "Life Is Beautiful",
  "Cinema Paradiso",
  "Pan's Labyrinth",
  "The Platform",
  "Downfall",
  "Run Lola Run",
  "The Lives of Others",
  "Das Boot",
  "The Artist",

  // --- CHINESE AND HONG KONG ---
  "Shaolin Soccer",
  "Ip Man",
  "Drunken Master",
  "Police Story",

  // --- OTHER ---
  "Children of Heaven",
  "City of God",
  "A Separation",
  "Amores Perros",
  "Roma",
  "Monsoon Wedding",
  "Everything Everywhere All at Once",
]
